package main

import (
	"bytes"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

const marker = "generate:reset"

type StructInfo struct {
	Name   string
	Fields []*ast.Field
	Pkg    string
	Dir    string
}

type TemplateStruct struct {
	Name   string
	Fields []FieldInfo
}

type FieldInfo struct {
	Code string
}

var fileTemplate = template.Must(template.New("file").Parse(`
// Code generated by reset generator. DO NOT EDIT.

package {{ .Pkg }}

{{ range .Structs }}
func (r *{{ .Name }}) Reset() {
	if r == nil {
		return
	}

{{ range .Fields }}
{{ .Code }}
{{ end }}
}
{{ end }}
`))

func main() {
	root := "."

	var structs []StructInfo

	fset := token.NewFileSet()

	filepath.WalkDir(root, func(path string, d os.DirEntry, err error) error {

		if err != nil || d.IsDir() {
			return nil
		}

		if !strings.HasSuffix(path, ".go") || strings.HasSuffix(path, ".gen.go") {
			return nil
		}

		file, err := parser.ParseFile(fset, path, nil, parser.ParseComments)
		if err != nil {
			return nil
		}

		found := findStructs(file)

		for _, s := range found {
			s.Pkg = file.Name.Name
			s.Dir = filepath.Dir(path)
			structs = append(structs, s)
		}

		return nil
	})

	grouped := map[string][]StructInfo{}

	for _, s := range structs {
		grouped[s.Dir] = append(grouped[s.Dir], s)
	}

	for dir, list := range grouped {

		var buf bytes.Buffer

		var tplStructs []TemplateStruct

		for _, s := range list {
			tplStructs = append(tplStructs, TemplateStruct{
				Name:   s.Name,
				Fields: buildFields(s.Fields),
			})
		}

		data := struct {
			Pkg     string
			Structs []TemplateStruct
		}{
			Pkg:     list[0].Pkg,
			Structs: tplStructs,
		}

		_ = fileTemplate.Execute(&buf, data)

		formatted, err := format.Source(buf.Bytes())
		if err != nil {
			formatted = buf.Bytes()
		}

		file := filepath.Join(dir, "reset.gen.go")

		_ = os.WriteFile(file, formatted, 0644)
	}
}

func findStructs(file *ast.File) []StructInfo {

	var result []StructInfo

	for _, decl := range file.Decls {

		genDecl, ok := decl.(*ast.GenDecl)
		if !ok || genDecl.Doc == nil {
			continue
		}

		hasMarker := false

		for _, c := range genDecl.Doc.List {
			if strings.Contains(c.Text, marker) {
				hasMarker = true
				break
			}
		}

		if !hasMarker {
			continue
		}

		for _, spec := range genDecl.Specs {

			typeSpec, ok := spec.(*ast.TypeSpec)
			if !ok {
				continue
			}

			st, ok := typeSpec.Type.(*ast.StructType)
			if !ok {
				continue
			}

			result = append(result, StructInfo{
				Name:   typeSpec.Name.Name,
				Fields: st.Fields.List,
			})
		}
	}

	return result
}

func buildFields(fields []*ast.Field) []FieldInfo {

	var result []FieldInfo

	for _, field := range fields {

		if len(field.Names) == 0 {
			continue
		}

		name := field.Names[0].Name

		code := buildFieldCode(name, field.Type)

		if code != "" {
			result = append(result, FieldInfo{
				Code: "\t" + code,
			})
		}
	}

	return result
}

func buildFieldCode(name string, expr ast.Expr) string {

	switch t := expr.(type) {

	case *ast.Ident:

		switch t.Name {
		case "int", "int32", "int64":
			return "r." + name + " = 0"

		case "string":
			return `r.` + name + ` = ""`

		case "bool":
			return "r." + name + " = false"
		}

	case *ast.ArrayType:

		return `if r.` + name + ` != nil {
		r.` + name + ` = r.` + name + `[:0]
	}`

	case *ast.MapType:

		return "clear(r." + name + ")"

	case *ast.StarExpr:

		if inner, ok := t.X.(*ast.Ident); ok {

			switch inner.Name {

			case "string":
				return `if r.` + name + ` != nil {
		*r.` + name + ` = ""
	}`

			case "int", "int32", "int64":
				return `if r.` + name + ` != nil {
		*r.` + name + ` = 0
	}`

			case "bool":
				return `if r.` + name + ` != nil {
		*r.` + name + ` = false
	}`

			default:

				return `if r.` + name + ` != nil {
		if resetter, ok := interface{}(r.` + name + `).(interface{ Reset() }); ok {
			resetter.Reset()
		}
	}`
			}
		}
	}

	return ""
}
