package main

import (
	"bytes"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"
)

const marker = "generate:reset"

type StructInfo struct {
	Name   string
	Fields []*ast.Field
	Pkg    string
	Dir    string
}

func main() {
	root := "."

	var structs []StructInfo

	fset := token.NewFileSet()

	filepath.WalkDir(root, func(path string, d os.DirEntry, err error) error {

		if err != nil {
			return nil
		}

		if d.IsDir() {
			return nil
		}

		if !strings.HasSuffix(path, ".go") {
			return nil
		}

		if strings.HasSuffix(path, ".gen.go") {
			return nil
		}

		file, err := parser.ParseFile(fset, path, nil, parser.ParseComments)
		if err != nil {
			return nil
		}

		found := findStructs(file)

		for _, s := range found {
			s.Dir = filepath.Dir(path)
			s.Pkg = file.Name.Name
			structs = append(structs, s)
		}

		return nil
	})

	grouped := map[string][]StructInfo{}

	for _, s := range structs {
		grouped[s.Dir] = append(grouped[s.Dir], s)
	}

	for dir, list := range grouped {

		var buf bytes.Buffer

		buf.WriteString("// Code generated by reset generator. DO NOT EDIT.\n\n")
		buf.WriteString("package " + list[0].Pkg + "\n\n")

		for _, s := range list {
			generateReset(&buf, s)
		}

		formatted, err := format.Source(buf.Bytes())
		if err != nil {
			formatted = buf.Bytes()
		}

		file := filepath.Join(dir, "reset.gen.go")

		_ = os.WriteFile(file, formatted, 0644)
	}
}

func findStructs(file *ast.File) []StructInfo {

	var result []StructInfo

	for _, decl := range file.Decls {

		genDecl, ok := decl.(*ast.GenDecl)
		if !ok {
			continue
		}

		if genDecl.Doc == nil {
			continue
		}

		hasMarker := false

		for _, c := range genDecl.Doc.List {
			if strings.Contains(c.Text, marker) {
				hasMarker = true
				break
			}
		}

		if !hasMarker {
			continue
		}

		for _, spec := range genDecl.Specs {

			typeSpec, ok := spec.(*ast.TypeSpec)
			if !ok {
				continue
			}

			st, ok := typeSpec.Type.(*ast.StructType)
			if !ok {
				continue
			}

			result = append(result, StructInfo{
				Name:   typeSpec.Name.Name,
				Fields: st.Fields.List,
			})
		}
	}

	return result
}

func generateReset(buf *bytes.Buffer, s StructInfo) {

	buf.WriteString("func (r *" + s.Name + ") Reset() {\n")
	buf.WriteString("\tif r == nil {\n")
	buf.WriteString("\t\treturn\n")
	buf.WriteString("\t}\n\n")

	for _, field := range s.Fields {

		if len(field.Names) == 0 {
			continue
		}

		name := field.Names[0].Name

		switch t := field.Type.(type) {

		case *ast.Ident:

			switch t.Name {
			case "int", "int32", "int64":
				buf.WriteString("\tr." + name + " = 0\n")

			case "string":
				buf.WriteString("\tr." + name + " = \"\"\n")

			case "bool":
				buf.WriteString("\tr." + name + " = false\n")
			}

		case *ast.ArrayType:

			buf.WriteString("\tif r." + name + " != nil {\n")
			buf.WriteString("\t\tr." + name + " = r." + name + "[:0]\n")
			buf.WriteString("\t}\n")

		case *ast.MapType:

			buf.WriteString("\tclear(r." + name + ")\n")

		case *ast.StarExpr:

			switch inner := t.X.(type) {

			case *ast.Ident:

				switch inner.Name {

				case "string":
					buf.WriteString("\tif r." + name + " != nil {\n")
					buf.WriteString("\t\t*r." + name + " = \"\"\n")
					buf.WriteString("\t}\n")

				case "int", "int32", "int64":
					buf.WriteString("\tif r." + name + " != nil {\n")
					buf.WriteString("\t\t*r." + name + " = 0\n")
					buf.WriteString("\t}\n")

				case "bool":
					buf.WriteString("\tif r." + name + " != nil {\n")
					buf.WriteString("\t\t*r." + name + " = false\n")
					buf.WriteString("\t}\n")

				default:

					buf.WriteString("\tif r." + name + " != nil {\n")
					buf.WriteString("\t\tif resetter, ok := interface{}(r." + name + ").(interface{ Reset() }); ok {\n")
					buf.WriteString("\t\t\tresetter.Reset()\n")
					buf.WriteString("\t\t}\n")
					buf.WriteString("\t}\n")
				}
			}
		}
	}

	buf.WriteString("}\n\n")
}
